name: Test Suite

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    env:
      IOS_SIMULATOR_DEVICE: "iPhone 16"
      PROJECT_NAME: "OSInAppBrowserLib"                    # Name used for output files
      SCHEME_NAME: "OSInAppBrowserLib"                     # Xcode scheme to build/test
      XCODEPROJ_PATH: "OSInAppBrowserLib.xcodeproj"        # Path to .xcodeproj file
      COVERAGE_TARGET_FILTER: "OSInAppBrowserLib"          # Target name for coverage filtering
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          # Install SwiftLint
          if ! command -v swiftlint &> /dev/null; then
            brew install swiftlint
          fi
          
          # Install xcbeautify for better output formatting
          if ! command -v xcbeautify &> /dev/null; then
            brew install xcbeautify
          fi
          
          # Install slather for coverage conversion
          if ! gem list slather -i &> /dev/null; then
            gem install slather
          fi
          
      - name: Run Unit Tests
        run: |
          mkdir -p build/reports
          set -o pipefail
          xcodebuild test \
            -project ${{ env.XCODEPROJ_PATH }} \
            -scheme ${{ env.SCHEME_NAME }} \
            -destination "platform=iOS Simulator,name=${{ env.IOS_SIMULATOR_DEVICE }}" \
            -configuration Debug \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            SKIP_SCRIPT_PHASES=YES \
            CODE_SIGNING_ALLOWED=NO | xcbeautify --report junit --report-path build/reports/junit.xml

      - name: Extract Code Coverage
        run: |
          # Extract target-specific coverage percentage
          coverage_percentage=$(xcrun xccov view --report TestResults.xcresult | grep "${{ env.COVERAGE_TARGET_FILTER }}" | head -1 | grep -o '[0-9]\+\.[0-9]\+%' | head -1)
          
          if [ -n "$coverage_percentage" ]; then
            echo "✅ Code coverage (${{ env.COVERAGE_TARGET_FILTER }}): $coverage_percentage"
          else
            coverage_percentage="N/A"
            echo "⚠️ Could not extract coverage percentage for ${{ env.COVERAGE_TARGET_FILTER }}"
          fi
          
          # Save coverage to environment for later use
          echo "COVERAGE_PERCENTAGE=$coverage_percentage" >> $GITHUB_ENV

      - name: Generate Code Coverage Report for SonarQube
        run: |
          # Create sonar-reports directory
          mkdir -p sonar-reports
          
          # Use Slather to convert coverage to SonarQube format
          if slather coverage \
            --sonarqube-xml \
            --output-directory sonar-reports \
            --scheme ${{ env.SCHEME_NAME }} \
            ${{ env.XCODEPROJ_PATH }}; then
            
            # Verify coverage file was generated
            if [ -f "sonar-reports/sonarqube-generic-coverage.xml" ]; then
              echo "✅ Coverage converted successfully with Slather"
              echo "📄 Generated: sonar-reports/sonarqube-generic-coverage.xml"
            else
              echo "⚠️ Slather succeeded but output file not found in expected location"
              echo "📁 Files in sonar-reports:"
              ls -la sonar-reports/ || echo "Directory doesn't exist"
            fi
          else
            echo "❌ Slather failed to generate coverage report"
            echo "ℹ️ SonarCloud will run without coverage data"
            echo "🔍 This is usually due to no test coverage or build issues"
          fi
          
      - name: Run SwiftLint for SonarQube
        run: |
          swiftlint --reporter checkstyle > sonar-reports/${{ env.PROJECT_NAME }}-swiftlint.xml || true
          
      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v8
        
      - name: Send to SonarCloud
        id: sonarcloud
        continue-on-error: true
        run: |
          if [ -f "sonar-project.properties" ]; then
            SONAR_PROJECT_KEY=$(grep "^sonar.projectKey=" sonar-project.properties | cut -d'=' -f2)
            echo "🔍 Attempting to send results to SonarCloud..."
            echo "📋 Project Key: $SONAR_PROJECT_KEY"
            echo "🌿 Branch: ${{ github.ref_name }}"
            
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.branch.name=${{ github.ref_name }} \
              -Dsonar.projectVersion=${{ github.sha }}
          else
            echo "⚠️ sonar-project.properties not found, skipping SonarCloud upload"
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            TestResults.xcresult
            sonar-reports/
            build/reports/
        
      - name: Comment Test Results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            
            // Get Xcode version dynamically
            const xcodeVersion = execSync('xcodebuild -version | head -1', { encoding: 'utf8' }).trim();
            
            // Get coverage percentage from environment
            const coveragePercentage = process.env.COVERAGE_PERCENTAGE || 'N/A';
            
            // Check if SonarCloud step succeeded by checking job status
            const sonarStepSucceeded = '${{ steps.sonarcloud.outcome }}' === 'success';
            
            // Dynamic message based on SonarCloud success/failure
            const sonarMessage = sonarStepSucceeded 
              ? '☁️ **SonarCloud**: Analysis completed - [View detailed report →](https://sonarcloud.io)'
              : '⚠️ **SonarCloud**: Upload failed - check workflow logs for details';
            
            const nextStepsMessage = sonarStepSucceeded
              ? '📋 **Next Steps**: Review the SonarCloud analysis for code quality insights and coverage details.'
              : '📋 **Next Steps**: Coverage data is available in test artifacts. SonarCloud integration needs attention.';
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🧪 Test Results

              ✅ **Tests**: All tests passed successfully!
              📊 **Code Coverage**: ${coveragePercentage}
              ${sonarMessage}

              **Environment:**
              - ${xcodeVersion}
              - iOS Simulator (${{ env.IOS_SIMULATOR_DEVICE }})
              - macOS runner: ${{ runner.os }}
              
              ${nextStepsMessage}`
            });
